//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoSubscriptionAccounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        public Publication()
        {
            this.Deliveries = new HashSet<Delivery>();
        }
    
        public int Id { get; set; }
        public string PublicationIndex { get; set; }
        public int IdPublicationType { get; set; }
        public string Title { get; set; }
        public double Price { get; set; }
    
        public virtual ICollection<Delivery> Deliveries { get; set; }
        public virtual PublicationType PublicationType { get; set; }
    }
}
